### ISSUE TITLE
Using it as a home manager module without flakes

### ISSUE THREAD

**Issue by PassiveLemon** [the-argus/spicetify-nix#11]
This seems like it's only really meant for flakes. I don't currently plan on using flakes any time soon so I was curious if there is an obvious way to just allow it to be an imported module? I am not very familiar with the Nix language so I am unsure how to do this myself.

**Comment by the-argus** [comment]
```nix
{config, pkgs, ...}: let
  flake-compat = builtins.fetchTarball "https://github.com/edolstra/flake-compat/archive/master.tar.gz";
  spicetify-nix = (import flake-compat {
    src = builtins.fetchTarball "https://github.com/the-argus/spicetify-nix/archive/master.tar.gz";
  }).defaultNix;
in {
  imports = [ spicetify-nix.homeManagerModule ];
  programs.spicetify = {
    # insert your configuration here...
  };
}
```
This is an example module which is totally untested but I think it should work. You'll probably want to switch to [pkgs.fetchgit](https://ryantm.github.io/nixpkgs/builders/fetchers/#fetchgit) (or pkgs.fetchFromGitHub if you prefer) instead of builtins.fetchTarball, so that way you can more easily update and maintain purity.

**Comment by PassiveLemon** [comment]
There was one small issue where I couldn't get it to run because it complained about not having a theme. I had to add `spicePkgs = spicetify-nix.packages.${pkgs.system}.default;` in the `let ... in` part to be able to use the themes.
Final module looked like:
```
{config, pkgs, ...}: let
  flake-compat = builtins.fetchTarball "https://github.com/edolstra/flake-compat/archive/master.tar.gz";
  spicetify-nix = (import flake-compat {
    src = builtins.fetchTarball "https://github.com/the-argus/spicetify-nix/archive/master.tar.gz";
  }).defaultNix;
  spicePkgs = spicetify-nix.packages.${pkgs.system}.default;
in {
  imports = [ spicetify-nix.homeManagerModule ];
  programs.spicetify = {
    enable = true;
    theme = spicePkgs.themes.catppuccin-mocha;
  };
}
```
After adding that line, it worked perfectly! Thank you
