### ISSUE TITLE
error: infinite recursion encountered

### ISSUE THREAD

**Issue by dr460nf1r3** [the-argus/spicetify-nix#18]
Hey! 

I'm getting the following while trying to activate spicetify-nix:

~~~
❯ sudo nixos-rebuild switch -L
warning: updating lock file '/etc/nixos/flake.lock':
• Added input 'spicetify-nix':
    'github:the-argus/spicetify-nix/ec85c2a2f5d1035142b8e383cc77b68bb0b9ebc8' (2023-02-07)
• Added input 'spicetify-nix/nixpkgs':
    'github:NixOS/nixpkgs/914ef51ffa88d9b386c71bdc88bffc5273c08ada' (2022-06-12)
building the system configuration...
error: infinite recursion encountered

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:483:28:

          482|         builtins.addErrorContext (context name)
          483|           (args.${name} or config._module.args.${name})
             |                            ^
          484|       ) (lib.functionArgs f);
(use '--show-trace' to show detailed location information)
~~~
My spicetify-nix config can be found [here](https://github.com/dr460nf1r3/device-configurations/commit/52b259e8b6a6c3d71352a9f28b35db04d2f9cba4#diff-0171f9a199bbe51257c8b36153a003603952eb69d71084e7faf4ee7c4e1b19e5R45). It also includes my system configuration.

The trace:

<details>
  <summary>Click me</summary>

  ❯ sudo nixos-rebuild switch -L --impure --show-trace
  building the system configuration...
  error:
       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/attrsets.nix:716:24:

          715|     let f = attrPath:
          716|       zipAttrsWith (n: values:
             |                        ^
          717|         let here = attrPath ++ [n]; in

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling 'g'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/attrsets.nix:535:19:

          534|           g =
          535|             name: value:
             |                   ^
          536|             if isAttrs value && cond value

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/attrsets.nix:538:20:

          537|               then recurse (path ++ [name]) value
          538|               else f (path ++ [name]) value;
             |                    ^
          539|         in mapAttrs g;

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:270:72:

          269|           # For definitions that have an associated option
          270|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          271|

       … while evaluating the attribute 'value'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:728:9:

          727|     in warnDeprecation opt //
          728|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          729|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating the attribute 'mergedValue'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:763:5:

          762|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          763|     mergedValue =
             |     ^
          764|       if isDefined then

       … while evaluating the attribute 'values'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:757:9:

          756|       in {
          757|         values = defs''';
             |         ^
          758|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:856:7:

          855|     in {
          856|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          857|       inherit highestPrio;

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:743:17:

          742|         # Process mkMerge and mkIf properties.
          743|         defs' = concatMap (m:
             |                 ^
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:743:28:

          742|         # Process mkMerge and mkIf properties.
          743|         defs' = concatMap (m:
             |                            ^
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:744:137:

          743|         defs' = concatMap (m:
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          745|         ) defs;

       … while calling 'dischargeProperties'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:815:25:

          814|   */
          815|   dischargeProperties = def:
             |                         ^
          816|     if def._type or "" == "merge" then

       … while evaluating the attribute 'value'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:568:44:

          567|       defnsByName' = byName "config" (module: value:
          568|           [{ inherit (module) file; inherit value; }]
             |                                            ^
          569|         ) configs;

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/nixos/modules/system/activation/top-level.nix:129:12:

          128|   # Replace runtime dependencies
          129|   system = foldr ({ oldDependency, newDependency }: drv:
             |            ^
          130|       pkgs.replaceDependency { inherit oldDependency newDependency drv; }

       … while calling 'foldr'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/lists.nix:53:20:

           52|   */
           53|   foldr = op: nul: list:
             |                    ^
           54|     let

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/lists.nix:60:8:

           59|         else op (elemAt list n) (fold' (n + 1));
           60|     in fold' 0;
             |        ^
           61|

       … while calling 'fold''

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/lists.nix:56:15:

           55|       len = length list;
           56|       fold' = n:
             |               ^
           57|         if n == len

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling 'g'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/attrsets.nix:535:19:

          534|           g =
          535|             name: value:
             |                   ^
          536|             if isAttrs value && cond value

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/attrsets.nix:538:20:

          537|               then recurse (path ++ [name]) value
          538|               else f (path ++ [name]) value;
             |                    ^
          539|         in mapAttrs g;

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:270:72:

          269|           # For definitions that have an associated option
          270|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          271|

       … while evaluating the attribute 'value'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:728:9:

          727|     in warnDeprecation opt //
          728|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          729|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `assertions':

       … while evaluating the attribute 'mergedValue'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:763:5:

          762|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          763|     mergedValue =
             |     ^
          764|       if isDefined then

       … while evaluating the attribute 'values'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:757:9:

          756|       in {
          757|         values = defs''';
             |         ^
          758|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:856:7:

          855|     in {
          856|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          857|       inherit highestPrio;

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:743:17:

          742|         # Process mkMerge and mkIf properties.
          743|         defs' = concatMap (m:
             |                 ^
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:743:28:

          742|         # Process mkMerge and mkIf properties.
          743|         defs' = concatMap (m:
             |                            ^
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/m0vk4rgrh9b0mn566330flhb94xfiqdx-source/nixos/common.nix':

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:744:137:

          743|         defs' = concatMap (m:
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          745|         ) defs;

       … while calling 'dischargeProperties'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:815:25:

          814|   */
          815|   dischargeProperties = def:
             |                         ^
          816|     if def._type or "" == "merge" then

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:821:11:

          820|         if def.condition then
          821|           dischargeProperties def.content
             |           ^
          822|         else

       … while calling 'dischargeProperties'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:815:25:

          814|   */
          815|   dischargeProperties = def:
             |                         ^
          816|     if def._type or "" == "merge" then

       … while evaluating the attribute 'content'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:886:14:

          885|     { _type = "if";
          886|       inherit condition content;
             |              ^
          887|     };

       … while evaluating call site

       at /nix/store/m0vk4rgrh9b0mn566330flhb94xfiqdx-source/nixos/common.nix:103:18:

          102|
          103|     assertions = flatten (flip mapAttrsToList cfg.users (user: config:
             |                  ^
          104|       flip map config.assertions (assertion: {

       … while calling 'flatten'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/lists.nix:138:13:

          137|   */
          138|   flatten = x:
             |             ^
          139|     if isList x

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/lists.nix:140:10:

          139|     if isList x
          140|     then concatMap (y: flatten y) x
             |          ^
          141|     else [x];

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/lists.nix:140:21:

          139|     if isList x
          140|     then concatMap (y: flatten y) x
             |                     ^
          141|     else [x];

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/lists.nix:140:24:

          139|     if isList x
          140|     then concatMap (y: flatten y) x
             |                        ^
          141|     else [x];

       … while calling 'flatten'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/lists.nix:138:13:

          137|   */
          138|   flatten = x:
             |             ^
          139|     if isList x

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/attrsets.nix:479:10:

          478|     attrs:
          479|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          480|

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/attrsets.nix:479:16:

          478|     attrs:
          479|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          480|

       … while calling anonymous lambda

       at /nix/store/m0vk4rgrh9b0mn566330flhb94xfiqdx-source/nixos/common.nix:103:64:

          102|
          103|     assertions = flatten (flip mapAttrsToList cfg.users (user: config:
             |                                                                ^
          104|       flip map config.assertions (assertion: {

       … while evaluating call site

       at /nix/store/m0vk4rgrh9b0mn566330flhb94xfiqdx-source/nixos/common.nix:104:7:

          103|     assertions = flatten (flip mapAttrsToList cfg.users (user: config:
          104|       flip map config.assertions (assertion: {
             |       ^
          105|         inherit (assertion) assertion;

       … while calling 'flip'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/trivial.nix:138:16:

          137|   */
          138|   flip = f: a: b: f b a;
             |                ^
          139|

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/types.nix:522:22:

          521|       merge = loc: defs:
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                      ^
          523|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … while evaluating the attribute 'value'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:776:27:

          775|     optionalValue =
          776|       if isDefined then { value = mergedValue; }
             |                           ^
          777|       else {};

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:765:59:

          764|       if isDefined then
          765|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          766|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while calling 'merge'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/types.nix:742:22:

          741|         check = x: isAttrs x || isFunction x || path.check x;
          742|         merge = loc: defs:
             |                      ^
          743|           (base.extendModules {

       … while evaluating the attribute 'config'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:346:9:

          345|         options = checked options;
          346|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          347|         _module = checked (config._module);

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:270:28:

          269|           # For definitions that have an associated option
          270|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                            ^
          271|

       … while calling 'mapAttrsRecursiveCond'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/attrsets.nix:530:5:

          529|     # Attribute set to recursively map over.
          530|     set:
             |     ^
          531|     let

       … while evaluating the attribute 'matchedOptions'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:637:14:

          636|     in {
          637|       inherit matchedOptions;
             |              ^
          638|

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:559:21:

          558|       # an attrset 'name' => list of submodules that declare ‘name’.
          559|       declsByName = byName "options" (module: option:
             |                     ^
          560|           [{ inherit (module) _file; options = option; }]

       … while calling 'byName'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:542:25:

          541|       */
          542|       byName = attr: f: modules:
             |                         ^
          543|         zipAttrsWith (n: concatLists)

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:262:33:

          261|           ({ inherit lib options config specialArgs; } // specialArgs);
          262|         in mergeModules prefix (reverseList collected);
             |                                 ^
          263|

       … while calling 'reverseList'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/lists.nix:406:17:

          405|   */
          406|   reverseList = xs:
             |                 ^
          407|     let l = length xs; in genList (n: elemAt xs (l - n - 1)) l;

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:258:25:

          257|       merged =
          258|         let collected = collectModules
             |                         ^
          259|           (specialArgs.modulesPath or "")

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:425:37:

          424|
          425|     in modulesPath: initialModules: args:
             |                                     ^
          426|       filterModules modulesPath (collectStructuredModules unknownModule "" initialModules args);

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:426:7:

          425|     in modulesPath: initialModules: args:
          426|       filterModules modulesPath (collectStructuredModules unknownModule "" initialModules args);
             |       ^
          427|

       … while calling 'filterModules'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:413:36:

          412|       # modules recursively. It returns the final list of unique-by-key modules
          413|       filterModules = modulesPath: { disabled, modules }:
             |                                    ^
          414|         let

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:419:31:

          418|           disabledKeys = map moduleKey disabled;
          419|           keyFilter = filter (attrs: ! elem attrs.key disabledKeys);
             |                               ^
          420|         in map (attrs: attrs.module) (builtins.genericClosure {

       … while evaluating the attribute 'disabled'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:395:13:

          394|           collectResults = modules: {
          395|             disabled = concatLists (catAttrs "disabled" modules);
             |             ^
          396|             inherit modules;

       … while evaluating the attribute 'disabled'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:395:13:

          394|           collectResults = modules: {
          395|             disabled = concatLists (catAttrs "disabled" modules);
             |             ^
          396|             inherit modules;

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:400:22:

          399|           let
          400|             module = loadModule args parentFile "${parentKey}:anon-${toString n}" x;
             |                      ^
          401|             collectedImports = collectStructuredModules module._file module.key module.imports args;

       … while calling 'loadModule'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:359:53:

          358|       # Like unifyModuleSyntax, but also imports paths and calls functions if necessary
          359|       loadModule = args: fallbackFile: fallbackKey: m:
             |                                                     ^
          360|         if isFunction m || isAttrs m then

       … while evaluating call site

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:360:12:

          359|       loadModule = args: fallbackFile: fallbackKey: m:
          360|         if isFunction m || isAttrs m then
             |            ^
          361|           unifyModuleSyntax fallbackFile fallbackKey (applyModuleArgsIfFunction fallbackKey m args)

       … while calling 'isFunction'

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/trivial.nix:448:16:

          447|   */
          448|   isFunction = f: builtins.isFunction f ||
             |                ^
          449|     (f ? __functor && isFunction (f.__functor f));

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:481:44:

          480|       context = name: ''while evaluating the module argument `${name}' in "${key}":'';
          481|       extraArgs = builtins.mapAttrs (name: _:
             |                                            ^
          482|         builtins.addErrorContext (context name)

       … while evaluating the module argument `spicetify-nix' in ":anon-6:anon-1":

       error: infinite recursion encountered

       at /nix/store/qilsyakhi0qmjq9iwxn49g3qbl1rp5m7-source/lib/modules.nix:483:28:

          482|         builtins.addErrorContext (context name)
          483|           (args.${name} or config._module.args.${name})
             |                            ^
          484|       ) (lib.functionArgs f);

</details>

**Comment by Vagahbond** [comment]
I have exactly the same issue

**Comment by Gamero-hub** [comment]
Also I have exactly the same issue

**Comment by the-argus** [comment]
@Vagahbond @Gamero-hub are your NixOS configurations similar to @dr460nf1r3 ? They have something that looks like this in their configuration.nix:

```
  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    users.nico = import ../home/nico.nix;
  };
```

And ``nico.nix`` contains the spicetify configuration as seen in the README.md for this repo.

This is not the way that I encouraged people to use spicetify-nix but it _should_ work. Just let me know if you're also using it.

**Comment by Vagahbond** [comment]
> @Vagahbond @Gamero-hub are your NixOS configurations similar to @dr460nf1r3 ? They have something that looks like this in their configuration.nix:
> 
> ```
>   home-manager = {
>     useGlobalPkgs = true;
>     useUserPackages = true;
>     users.nico = import ../home/nico.nix;
>   };
> ```
> 
> And ``nico.nix`` contains the spicetify configuration as seen in the README.md for this repo.
> 
> This is not the way that I encouraged people to use spicetify-nix but it _should_ work. Just let me know if you're also using it.

Hello, thanks a lot for your help, i just figured out I didn't import the flake the right way, and I tried using it in the main configuration, not home manager. Now it works for me. Thanks a lot for your concern and help!

**Comment by the-argus** [comment]
Okay great. I recommend everyone look at the way that you've imported spicetify and consider changing it (use it as a NixOS module instead of a home-manager module). Let me know if you see any differences.

**Comment by dr460nf1r3** [comment]
Alright, I understood the instructions the wrong way then. I did the following now:
1. Add spicetify to outputs & defaultModules in in flake.nix
2. Add the relevant part of the home-manager config 

Now I'm getting the following error (which seems directly related to this, as all other changes build fine):
```
error: The option `default' does not exist. Definition values:
       - In `/nix/store/2g0ybkz5ka44rn3mr98kd667nk7w3zq3-source/flake.nix': <function, args: {config, lib, pkgs}>
```
I apologize, if I'm not seeing the obvious fix 😅

**Comment by dr460nf1r3** [comment]
Oops.

**Comment by the-argus** [comment]
@dr460nf1r3 Could you please send a link to the commit where you tried this?

I'm not certain, but I believe one thing is that you should not add spicetify.homeManagerModule to ``defaultModules`` because your ``defaultModules`` are imported both but nixOS configs and home manager.

**Comment by dr460nf1r3** [comment]
I'm sharing here the commit, with your latest suggestion applied. https://github.com/dr460nf1r3/device-configurations/commit/54df360deff0af11f03c4be87497dc9fbf40c8e8

Interestingly, this leads to a different issue, though the file seems to be the same flake.nix hinted to. I appreciate the help :) 

```
error: The option `home' does not exist. Definition values:
       - In `/nix/store/y34pw71w25ay4j5bm5239m8gw0pp4w63-source/flake.nix':
           {
             _type = "if";
             condition = false;
             content = {
               packages = [
           ...
```

**Comment by Gamero-hub** [comment]
Well, I copied the config from a guy on github and I can now use spicetify-nix without errors (I don't know if it's the best way to use it but there it is) (after this I added it to flake.nix in the home-manager imports)
```{ config, pkgs, ...}:
let
  flake-compat = builtins.fetchTarball "https://github.com/edolstra/flake-compat/archive/master.tar.gz";
  spicetify-nix = (import flake-compat { src = builtins.fetchTarball "https://github.com/the-argus/spicetify-nix/archive/master.tar.gz"; }).defaultNix;
  spicePkgs = spicetify-nix.packages.${pkgs.system}.default;
in
{
  imports = [ spicetify-nix.homeManagerModule ];
  programs.spicetify = {
    enable = true;
    theme = spicePkgs.themes.DefaultDynamic;
    enabledExtensions = with spicePkgs.extensions; [
      autoSkipVideo
      seekSong
      adblock
    ];
  };
}

**Comment by dr460nf1r3** [comment]
Yay!! This actually made it work after sha256sums 😁 

![image](https://user-images.githubusercontent.com/12834713/227010586-09fe3ba0-a884-4d7b-bf3c-bccd9b99553b.png)

So basically, this is the commit enabled it for me: https://github.com/dr460nf1r3/device-configurations/commit/8f8d4fc67f72bec5805ac2b40471e8ebbd2390ff

That being said, I'm not familiar enough with NixOS yet to really understand why this worked but the other ways didn't. Thanks for your time @the-argus and @Gamero-hub for the hint!

**Comment by the-argus** [comment]
Very odd... I thought you were already using a flake configuration. I see no reason why you needed flake compat to eliminate infinite recursion. Hopefully at some point I'll find the time to ask around and find someone who can explain why this happened. In the meantime, this is a working solution so I'm leaving the issue closed.

**Comment by dr460nf1r3** [comment]
I was in fact using a flake configuration, so I was confused as well 👀 it's great to have it working, which is good enough for me 😀 thanks for maintaining this project!

**Comment by Amanse** [comment]
for everyone who is using home-manager standalone version with flakes, importing it in modules section fixes the issue
```nix
    {
      homeConfigurations.me = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;

        # Specify your home configuration modules here, for example,
        # the path to your home.nix.
        modules = [
          ./home
          spicetify-nix.homeManagerModule
          {
            programs.spicetify = {
              enable = true;
              theme = spicetify-nix.packages.${pkgs.system}.default.themes.Ziro;
            };
          }
        ];

        # Optionally use extraSpecialArgs
        # to pass through arguments to home.nix
      };
    };
```

**Comment by allusive-dev** [comment]
> Yay!! This actually made it work after sha256sums 😁
> 
> ![image](https://user-images.githubusercontent.com/12834713/227010586-09fe3ba0-a884-4d7b-bf3c-bccd9b99553b.png)
> 
> So basically, this is the commit enabled it for me: [dr460nf1r3/dr460nixed@8f8d4fc](https://github.com/dr460nf1r3/dr460nixed/commit/8f8d4fc67f72bec5805ac2b40471e8ebbd2390ff)
> 
> That being said, I'm not familiar enough with NixOS yet to really understand why this worked but the other ways didn't. Thanks for your time @the-argus and @Gamero-hub for the hint!

How do you pass in the sha256 arguments and what are they?
