### ISSUE TITLE
Catppuccin theme is not consistent

### ISSUE THREAD

**Issue by fufexan** [the-argus/spicetify-nix#20]
In newer versions of Spotify (I'm on `1.2.8.923.g4f94bf0d`), the Catppuccin theme has "greyed out" colors for some of the text and icons, mostly visible in the friends tab and on the song controls.
![image](https://user-images.githubusercontent.com/36706276/236331772-aa97d0f9-48e1-4618-9d8c-00f0911d4a47.png)

**Comment by the-argus** [comment]
@fufexan This may be fixed as of c1abe3d (spicetify and catpuccin updates). Try updating your flake inputs and see how it looks.

**Comment by fufexan** [comment]
Thank you, this is better!
![image](https://user-images.githubusercontent.com/36706276/236705438-7e89ac94-0533-4281-9fe5-406014a8a202.png)
