### ISSUE TITLE
marketplace: Something went wrong

### ISSUE THREAD

**Issue by jtojnar** [the-argus/spicetify-nix#22]
After recent update https://github.com/the-argus/spicetify-nix/compare/f89305a9af65abf3edfba10d12c2d1a572caddb6...c1abe3d0bc44868e4ba04e3fccce7b620522ab5e, I see the following when building spotify:

```
spotify> Transferring custom apps:
spotify> error Custom app "marketplace" does not have index.js
```

The Marketplace is still in the menu but clicking it shows “Something went wrong” page.

I am using the following in my home-manager config:

```nix
    programs.spicetify = {
      enable = true;
      theme = pkgs.spicePkgs.themes.Default;

      enabledCustomApps = with pkgs.spicePkgs.apps; [
        lyrics-plus
        marketplace
      ];

      enabledExtensions = with pkgs.spicePkgs.extensions; [
        playNext
        hidePodcasts
      ];
    };
```

**Comment by the-argus** [comment]
Looks like the file structure upstream changed. Will look into it in the next day or so. In the meantime, I recommend rolling back your flake inputs.

**Comment by the-argus** [comment]
@jtojnar The source for marketplace wasn't using the ``dist`` branch. It's one of many things fixed in the most recent PR. Let me know if the build issue is fixed.

**Comment by the-argus** [comment]
Okay I lied last time, but as of #24 it should _actually_ be fixed.

**Comment by jtojnar** [comment]
Thanks. Can confirm.
