### ISSUE TITLE
Add rosepine themes

### ISSUE THREAD

**Issue by prescientmoon** [the-argus/spicetify-nix#27]
Hi! I'd love to be able to use the themes from [this repo](https://github.com/nicoleajoy/rose-pine-spotify)! I can try and add them myself although I am not sure how.

**Comment by the-argus** [comment]
@Mateiadrielrafael That repo is just for screenshots of the color scheme, the actual color schemes are [in the spicetify repo already](https://github.com/spicetify/spicetify-themes/blob/96d6cc6e6caba407a4c2acc2e0c1fb4a2acad583/Ziro/color.ini#L214). Here's an example config which uses one:

```nix
{ pkgs, lib, spicetify-nix, ... }:
let
  spicePkgs = spicetify-nix.packages.${pkgs.system}.default;
in
{
  # allow spotify to be installed if you don't have unfree enabled already
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "spotify"
  ];

  # import the flake's module for your system
  imports = [ spicetify-nix.homeManagerModule ];

  # configure spicetify :)
  programs.spicetify =
    {
      enable = true;
      theme = spicePkgs.themes.Ziro;
      colorScheme = "rose-pine-dawn";
    };
}
```

**Comment by the-argus** [comment]
May reopen if this isn't what you were describing in your request. lmk
