### ISSUE TITLE
Add pywal theme.

### ISSUE THREAD

**Issue by samiulbasirfahim** [the-argus/spicetify-nix#28]
I like to use pywal. But i couldn't able to find any way to use pywal theme on spicefity-nix.

**Comment by Gerg-L** [comment]
> I like to use pywal. But i couldn't able to find any way to use pywal theme on spicefity-nix.

you can use the `customColorScheme` option and [stylix](https://github.com/danth/stylix) or [base16.nix](https://github.com/SenchoPens/base16.nix)

**Comment by samiulbasirfahim** [comment]
Its kinda complicated,   Can I import color scheme on spicetify from .cache/wal ?

**Comment by the-argus** [comment]
@xenoxanite Unless you're running in impure mode (which I don't recommend) you can't access paths like `~/.cache` from a nix config. However, if you can figure out an acceptable way to pull your pywal colorscheme into nix config (maybe by just copying your .wal directory into your git repo and adding it), I'd be willing to implement a pywal color format -> customColorScheme function.

Also yeah, look at stylix. Stylix has a built in package which lets you commit a wallpaper to your nix repo and then select it as your theme source, and it will generate a color scheme from it which is usable in nix. It's basically a nix pywal.

**Comment by samiulbasirfahim** [comment]
> @xenoxanite Unless you're running in impure mode (which I don't recommend) you can't access paths like `~/.cache` from a nix config. However, if you can figure out an acceptable way to pull your pywal colorscheme into nix config (maybe by just copying your .wal directory into your git repo and adding it), I'd be willing to implement a pywal color format -> customColorScheme function.
> 
> Also yeah, look at stylix. Stylix has a built in package which lets you commit a wallpaper to your nix repo and then select it as your theme source, and it will generate a color scheme from it which is usable in nix. It's basically a nix pywal.

Im not getting it. I think if i can use a put a path of custom css file. It would be good for implement it with pywal. I
