### ISSUE TITLE
Themes with rendering issues

### ISSUE THREAD

**Issue by the-argus** [the-argus/spicetify-nix#31]
The following themes are currently broken with scaling/stretching issues (at a glance, from running all the tests and just looking at the homepage and one playlist):
- Flow
- Omni
- Fluent (more minor issues with the left panel being small and using squashed text instead of icons. the main panel is still usable)

Additionally, the following themes do not appear to apply at all:
- Glaze
- Bloom
- Turntable (full app display just appears normal. I think the theme isn't applying.)

Haven't looked into it. The first step is to make a non-nix spicetify installation and confirm that this issue is unique to nix.

**Comment by nonetrix** [comment]
Catppuccin might be effected now
![image](https://github.com/the-argus/spicetify-nix/assets/45698918/47301b38-26bf-4c66-8030-132bc7786a0c)

**Comment by nonetrix** [comment]
Also, could I pin Spotify to a old version and just use that? What version would work well? I feel like just doing that, not like they have added any surface level features I really give two craps about

**Comment by the-argus** [comment]
@nonetrix Thanks for noticing the issue, but I am no longer maintaining this flake! Migrate to https://github.com/Gerg-L/spicetify-nix (instructions in the readme for this project) and see if the issue persists there, and if so make an issue on that repository.  This one is being archived.
