### ISSUE TITLE
Spicetify not connecting to MPRIS

### ISSUE THREAD

**Issue by fufexan** [the-argus/spicetify-nix#36]
**Describe the bug**
When using Spicetify, opening Spotify as the first music player after booting the system, it does not appear in the MPRIS clients list. It *may* show up if you open a YouTube video then close it, or it may not.

The non-Spicetify version starts as a MPRIS client always, so it's not a Spotify issue.

**My config**
[Provide a [link](https://example.com) to your nix configuration. Alternatively, provide a `nix run` or `nix build` command which will replicate the issue.](https://github.com/fufexan/dotfiles/blob/ec598124085fac0dbdbe5b3cf733e8c66860da74/home/programs/spicetify.nix)

**Screenshots**
Not needed.

**Desktop (please complete the following information):**
 - OS/distro: NixOS 
 - Desktop environment/window manager: Hyprland
 - nixpkgs version for my home configuration: unstable `ce5e4a6ef2e59d89a971bc434ca8ca222b9c7f5e`
 - nixpkgs version for my import of spicetify nix: same as above

**Additional context**

**Comment by A1ca7raz** [comment]
It works fine on my machine. Is this bug still there? Did you checked your players by running `playerctl -l`?

**Comment by fufexan** [comment]
Yes. It seems to work now. I'll close the issue if it doesn't happen again in the next 2-3 boots.

**Comment by CnTeng** [comment]
It happend to me.
After boot, when the first starting spotify:
![image](https://github.com/the-argus/spicetify-nix/assets/56501688/84677643-20a0-4a7d-ac4f-a228e2b77656)
after starting chrome and playing yutube video:
![image](https://github.com/the-argus/spicetify-nix/assets/56501688/b531f9c2-13e1-4145-8474-43b76a1b7947)

And, if you restart playerctld service after boot, spotify can be find without playing youtube vedio.

Desktop environment/window manager: Hyprland
@fufexan

**Comment by the-argus** [comment]
Migrate to https://github.com/Gerg-L/spicetify-nix (instructions in the readme for this project) and see if the issue persists there, and if so make an issue on that repository.  This one is being archived.
