### ISSUE TITLE
Missing Config Options

### ISSUE THREAD

**Issue by aemogie** [the-argus/spicetify-nix#40]
**Describe the bug**
The config options for `inject_theme_js` (added in spicetify/spicetify-cli#2256) and `home_config` aren't available.

**My config**
N/A (and it's not public yet)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS/distro: NixOS
 - Desktop environment/window manager: Hyprland
 - nixpkgs version for my home configuration: unstable
 - nixpkgs version for my import of spicetify nix: unstable

**Additional context**
Found while looking through [`helpConfig` in `spicetify.go`](https://github.com/spicetify/spicetify-cli/blob/7c425319fa8bd655ac1718ce0fb23ba1e47e98de/spicetify.go#L446)

**Comment by the-argus** [comment]
@aemogie  Migrate to https://github.com/Gerg-L/spicetify-nix (instructions in the readme for this project) and see if the issue persists there, and if so make an issue on that repository.  This one is being archived.
