### ISSUE TITLE
Catppuccin color change

### ISSUE THREAD

**Issue by Philopateer2099** [the-argus/spicetify-nix#44]
I just updated to the newer version where now the package is just called catppuccin without the flavour and the color Scheme value is now the flavour how to set the accent?

**Comment by d-eni-s** [comment]
You can change the accent in the spotify settings, as described in the catppuccin spicetify documentation.

**Comment by Philopateer2099** [comment]
that doesn't work my entire settings just don't open any drop down at all just flickers the app is there another way?

**Comment by Philopateer2099** [comment]
nevermind i switch to kde to update settings and that worked i guess seems like a hyprland issue

**Comment by nonetrix** [comment]
I weirdly don't have anything in settings :/
![image](https://github.com/the-argus/spicetify-nix/assets/45698918/e33cb4e8-4e28-4858-9f85-b7d5f7cdf942)
Also theme looks slightly bugged seemingly unless it's meant to look like this which I don't like
![image](https://github.com/the-argus/spicetify-nix/assets/45698918/e1bf27be-6f7a-4e71-bf66-ee8b87806280)

**Comment by AlexNabokikh** [comment]
@nonetrix same... I had to switch to the forked alternative to solve the issue.

**Comment by nonetrix** [comment]
Will try that in the morning, going to bed for now. I updated my system and it wants to update ROCm related things again, could revert and try it but already 1AM lol. Yeah not staying up until 3AM because ROCm makes Chromium compile times seem reasonable lol

**Comment by nonetrix** [comment]
> @nonetrix same... I had to switch to the forked alternative to solve the issue.

Which fork? I tried this one which just seems to have bumped the version a few times, nothing changed
https://github.com/A1ca7raz/spicetify-nix

**Comment by AlexNabokikh** [comment]
> > @nonetrix same... I had to switch to the forked alternative to solve the issue.
> 
> Which fork? I tried this one which just seems to have bumped the version a few times, nothing changed
> https://github.com/A1ca7raz/spicetify-nix 

```
    spicetify-nix.url = "github:MichaelPachec0/spicetify-nix";
```

**Comment by nonetrix** [comment]
> MichaelPachec0/spicetify-nix

Still broken for me, but it did let me change the config at least
![image](https://github.com/the-argus/spicetify-nix/assets/45698918/654d8ab0-8d1c-4cae-9d9c-3db5e9345de3)
