### ISSUE TITLE
Genre extension broken

### ISSUE THREAD

**Issue by SystematicError** [the-argus/spicetify-nix#50]
**Describe the bug**
When including the `genre` extension, the build fails.

**My config**
```nix
{inputs, ...}: {
  imports = [ inputs.spicetify.homeManagerModule ];

  programs.spicetify = {
    enable = true;

    enabledExtensions = with inputs.spicetify.packages.x86_64-linux.default.extensions; [
      genre
    ];
  };
}
```

**Desktop (please complete the following information):**
 - OS/distro: NixOS unstable
 - Desktop environment/window manager: Hyprland
 - nixpkgs version for my home configuration:  unstable
 - nixpkgs version for my import of spicetify nix: same as above

**Additional context**
When trying to rebuild my home manager config, this is the trace that appears:
```
warning: Git tree '/etc/nixos' is dirty
warning: Git tree '/etc/nixos' is dirty
warning: Git tree '/etc/nixos' is dirty
error: builder for '/nix/store/qz72kbwxrl1lzxghd4gadfmgh5gn10pj-Spicetify-Genre-f2cb950.drv' failed with exit code 1;
       last 6 log lines:
       > exporting https://github.com/Shinyhero36/Spicetify-Genre (rev f2cb950a7e27cce3bfd4168141b5c5e55552df5a) into /nix/store/9sqg2p5n437j1dclmiwm82qa39vzrkkq-Spicetify-Genre-f2cb950
       > Initialized empty Git repository in /nix/store/9sqg2p5n437j1dclmiwm82qa39vzrkkq-Spicetify-Genre-f2cb950/.git/
       > fatal: could not read Username for 'https://github.com': No such device or address
       > fatal: could not read Username for 'https://github.com': No such device or address
       > fatal: could not read Username for 'https://github.com': No such device or address
       > Unable to checkout f2cb950a7e27cce3bfd4168141b5c5e55552df5a from https://github.com/Shinyhero36/Spicetify-Genre.
       For full logs, run 'nix log /nix/store/qz72kbwxrl1lzxghd4gadfmgh5gn10pj-Spicetify-Genre-f2cb950.drv'.
error: 1 dependencies of derivation '/nix/store/clfgr6ibm2dndbszh0q56h7s6di0dgq4-spicetify-Default.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f1907q3i52qg8iab9zsfgpjav0l74y7g-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/i0bzqz4vivnl0z403g9m09km75678m4q-home-manager-generation.drv' failed to build
```

The error message led me to check out the url causing the error (https://github.com/Shinyhero36/Spicetify-Genre) in my browser and turns it returns a 404. The plugin author probably deleted, moved, or made the plugin repository private.

**Comment by SystematicError** [comment]
There seems to be quite a few remote sources which the flake fetches from for building. Perhaps to prevent stuff like this in the future, unit tests could be written for each extension?

**Comment by Dokkae6949** [comment]
I had a quick look and it seems that a lot of genre plugins stopped working according to some guy on reddit.

So I found a new plugin on github [here](https://github.com/Vexcited/better-spotify-genres) Not sure what really happened tho.

**Comment by luisnquin** [comment]
I'm having the same issue, I had no option but to remove that extension :(

**Comment by the-argus** [comment]
@SystematicError @luisnquin @Dokkae6949 
Migrate to https://github.com/Gerg-L/spicetify-nix (instructions in the readme for this project) and see if the issue persists there, and if so make an issue on that repository.  This one is being archived.

I haven't tested it, but I believe I saw a commit on Gerg's flake adding a new genre extension recently. Should work
