### ISSUE TITLE
Lyrics plus app shows "Something went wrong"

### ISSUE THREAD

**Issue by diogotcorreia** [the-argus/spicetify-nix#51]
**Describe the bug**
When using the lyrics plus app, Spotify shows "Something went wrong" error.

**My config**

```nix
    hm.programs.spicetify = {
      enable = true;

      enabledCustomApps = with spicetifyPkgs.apps; [ lyrics-plus ];
    };
```

**Screenshots**
![image](https://github.com/the-argus/spicetify-nix/assets/7467891/f617798f-4555-4a6e-8323-a49ded7d972d)

**Desktop (please complete the following information):**
 - OS/distro: NixOS 23.11 (https://github.com/diogotcorreia/dotfiles)
 - Desktop environment/window manager: DWM
 - nixpkgs version for my home configuration: 23.11
 - nixpkgs version for my import of spicetify nix: "same as above"

**Additional context**
I'm guessing this is some kind of version incompatibility between the version of spotify and spicetify, since spicetify seems to be quite outdated.

Related issue: https://github.com/spicetify/spicetify-cli/issues/2672

Note: this has not been working for a while, I just haven't had to the patience to report it since I don't use the Spotify desktop app that much.

**Comment by the-argus** [comment]
@diogotcorreia Migrate to https://github.com/Gerg-L/spicetify-nix (instructions in the readme for this project) and see if the issue persists there, and if so make an issue on that repository.  This one is being archived.

I just tested lyricsPlus with Gerg's flake and it works fine and is fully up to date btw
