### ISSUE TITLE
Incorrect trace warnings

### ISSUE THREAD

**Issue by gekoke** [the-argus/spicetify-nix#52]
**Describe the bug**
[Minimal configuration](https://github.com/the-argus/spicetify-nix#minimal-configuration) outputs `trace: warning: spicetify-nix.lib is deprecated, use spicetify-nix.libs.${pkgs.system}` when evaluating, even though `spicetify-nix.lib` is not referenced.

**My config**
https://github.com/gekoke/dotfiles/blob/0d8af775ff9dc14673051b346de0b1a13bf27bcb/modules/nixos/programs/spotify/default.nix

**Screenshots**
![image](https://github.com/the-argus/spicetify-nix/assets/63151928/be7d5ef2-e30a-4d7a-9561-675b4b3bbd62)

**Desktop (please complete the following information):**
 - OS/distro: NixOS 24.05
 - Desktop environment/window manager: Hyprland
 - nixpkgs version for my home configuration: unstable
 - nixpkgs version for my import of spicetify nix: unstable
 
 Either the trace warning is incorrect, or the docs should provide an updated usage example.
 
 Thanks for providing this module!

**Comment by the-argus** [comment]
Migrate to https://github.com/Gerg-L/spicetify-nix (instructions in the readme for this project) and see if the issue persists there, and if so make an issue on that repository.  This one is being archived.

I think the readme was just out of date- the examples in the one on Gerg's flake should work fine.
