### ISSUE TITLE
`check_spicetify_upgrade` renamed to `check_spicetify_update`

### ISSUE THREAD

**Issue by aemogie** [the-argus/spicetify-nix#54]
**Describe the bug**

The option `check_spicetify_upgrade` was renamed to `check_spicetify_update` in the PR spicetify/spicetify-cli#2638

**My config**
\-

**Screenshots**
\-

**Desktop (please complete the following information):**
 - OS/distro: NixOS
 - Desktop environment/window manager: Hyprland
 - nixpkgs version for my home configuration: unstable
 - nixpkgs version for my import of spicetify nix: same as above

**Additional context**
\-

**Comment by the-argus** [comment]
Migrate to https://github.com/Gerg-L/spicetify-nix and see if the issue persists there. If so, make an issue on that repository- this one is being archived.
