### ISSUE TITLE
Local Files & Lyrics Integration Results in Crashes

### ISSUE THREAD

**Issue by ghost** [the-argus/spicetify-nix#55]
**Describe the bug**
--------------------------------------------
The application encounters a complete crash when either attempting to add a local files directory or when loading song lyrics from a file.

**Troubleshooting Attempts**
--------------------------------------------
I have tried the following code snippet in an effort to resolve the issue, but it has proven unsuccessful:

```
{          
   name = "localFiles";          
   src = "${config.home.homeDirectory}/Music";          
   appendName = false;        
}
```
I can't deny the possibility of my window or file manager to be the center of the issue. Nevertheless, I'm not sure why the above snippet isn't working as intended. Perhaps there's something I'm overlooking.

**Desktop**
--------------------------------------------
 - OS/distro: NixOS
 - Desktop environment/window manager: Hyprland
 - nixpkgs version for my home configuration: unstable
 - nixpkgs version for my import of spicetify nix: unstable

**Comment by the-argus** [comment]
Migrate to https://github.com/Gerg-L/spicetify-nix. This flake is being archived.

It looks like you are trying to set the source for the extension itself (ie the path to the localFiles extension's js code) to the folder with your local files. I am not sure what the correct way to handle this would be, I think your best bet is to read the docs of the new flake, or see if you can do it imperatively by installing localFiles and then specifying the folder from within spotify.
