### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by ItsDrike** [the-argus/spicetify-nix#62]
**Describe the bug**
Unable to build spicetify on latest nixpkgs (693bc46d169f5af9c992095736e82c3488bf7dbb)

**My config**
https://github.com/ItsDrike/nixdots/blob/main/home/programs/graphical/apps/spotify/default.nix

**Screenshots**
![image](https://github.com/user-attachments/assets/488a9ca3-5a8d-4174-84e6-5a1a6efaf282)

**Desktop (please complete the following information):**
 - OS/distro: NixOS
 - Desktop environment/window manager: Hyprland
 - nixpkgs version for my home configuration: unstable
 - nixpkgs version for my import of spicetify nix: unstable

**Additional context**

<details>
<summary>Error message transscript</summary>

```
error: builder for '/nix/store/4fadrn87d2wrhc2ybm7fiqfyvjd6dasq-spicetify-catppuccin.drv' failed with exit code 1;
       last 10 log lines:
       > Applying additional modifications:
       > OK
       > Transferring extensions:
       > success 09:07:05 All extensions are updated.
       > OK
       > Transferring custom apps:
       > OK
       > success Spotify is spiced up!
       > rm: cannot remove '/nix/store/2j4dnf91plzvgizzk5389zlxy8fyni48-spicetify-catppuccin/snap.yaml': No such file or directory
       > /nix/store/5r0df66ikad3xw06azlqvswcvncll8wa-stdenv-linux/setup: line 193: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/4fadrn87d2wrhc2ybm7fiqfyvjd6dasq-spicetify-catppuccin.drv'.
error: 1 dependencies of derivation '/nix/store/06sis7a56by3g58rsbqyx3bi2bm2pvll-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xp8djfdgpzh9vz72670dda04b2rfw9fv-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/p7p2mgj7dhz20060w3387icp7sj79xmp-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bhnq3g2yvhvk4zp5wl88m2dpj71xq88p-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/g848xg8sm3yvrwl2fkp3japyqr64dav4-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ghi3ldwg19p53cqz1g5cvyks7q7v3mk8-nixos-system-voyager-24.11.20240714.693bc46.drv' failed to build
```

</details>

**Comment by DADA30000** [comment]
@ItsDrike there is also a pull request that is ready for merging, and that fixes this problem, you can fork this repo and add those commits

**Comment by gigamonster256** [comment]
I've swapped to using https://github.com/Gerg-L/spicetify-nix which simplifies a lot of the packaging and has more recent additions/plugins.

**Comment by Ambioid** [comment]
> I've swapped to using https://github.com/Gerg-L/spicetify-nix which simplifies a lot of the packaging and has more recent additions/plugins.

Thanks, this fork seems to have fixed this issue and fixed and packaged a lot of extensions! How did you know about this one?

**Comment by gigamonster256** [comment]
> How did you know about this one?

I honestly can’t recall, I think I was trolling around looking for up to date forks and found a GitHub issue somewhere referencing the Gerg-L fork.
