### ISSUE TITLE
error: attribute 'additionalCss' missing

### ISSUE THREAD

**Issue by eyadsibai** [the-argus/spicetify-nix#7]
after updating to master. getting the error. Not sure where to define the additionalCss

**Comment by the-argus** [comment]
Include your spicetify config please.

This is a known issue with the fact that I allowed for defining themes with a string. I'm going to phase that out soon. In the meantime, I can look at your spicetify config and fix the issue for the theme you're using.

**Comment by the-argus** [comment]
closing as stale
